### ISSUE TITLE
Image asset fit icon

### ISSUE THREAD

**Issue by contrasting** [Nightmare-MY/shortcut#1]
Firstly thank you for your work on this package.

How can I make the image asset fit the icon? Currently it looks like this:

![Screenshot_1637406014](https://user-images.githubusercontent.com/40671177/142723901-749d3dbb-e6d1-4fcd-9bbc-23cf89051cd8.png)

I would like it to fit within the circle, kind of like `BoxFit.cover`:

![Screenshot_1637406014 - Copy](https://user-images.githubusercontent.com/40671177/142723911-9cdb5c03-e4e2-4797-aec7-8fa8f8fac245.png)

**Comment by Laurie-Lin** [comment]
This looks like designed by desktop launcher,u can see https://github.com/nightmare-space/shortcut/blob/2cc52d03896f82233d6761fc9abd1d2ae1db6868/android/src/main/java/com/nightmare/shortcut/ShortcutPlugin.java#L97,i didn't transform image,thank you for trying this package

**Comment by contrasting** [comment]
Ok thank you
